### ISSUE TITLE
Link color might be too light

### ISSUE THREAD

**Issue by vincentmvdm** [drstearns/tutorials#3]
The current link color [makes link text a bit too hard to read](http://jxnblk.com/colorable/demos/text/?background=%23fff&foreground=%2300d1b2). It might be worth it to override it with #00A88F (L: 41 -> L: 33), [which is somewhat better](http://jxnblk.com/colorable/demos/text/?background=%23fff&foreground=%2300A88F). Alternatively, Bulma has $info-invert (#3273dd), but that kind of ruins the color scheme.

**Comment by drstearns** [comment]
Yeah, I agree. I've always thought Bulma's default link color was too light. I'm already hacking it to avoid some conflicts with Prism.css, so I'll change the link color as well. And I like your color suggestion!

**Comment by drstearns** [comment]
OK, I changed the link color to what you suggested. Let me know if you think it works. If not, feel free to reopen with a different suggested color. Make sure you do a hard-refresh on the browser to force it to re-download `lib/bulma.min.css`.
