### ISSUE TITLE
Node.js Microservices: body-parser might not be necessary anymore

### ISSUE THREAD

**Issue by vincentmvdm** [drstearns/tutorials#6]
Express just released express.json/express.urlencoded (https://github.com/expressjs/express/releases/tag/4.16.0). It seems like those could replace the body-parser dependency.

**Comment by drstearns** [comment]
Interesting! Looks like they moved the JSON `body-parser` into the `express` package itself at version `4.16`. Makes sense given that JSON-based API servers are now the norm. I'll update the tutorial to reflect this. Using `body-parser` still works, but it's no longer necessary, so I can simplify the code by using the built-in JSON parser middleware instead.
