### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by vincentmvdm** [drstearns/tutorials#7]
Hey!

I just noticed that there seems to be a broken link in this tutorial: https://drstearns.github.io/tutorials/deploy2aws/. The text "Running Let's Encrypt on Amazon Linux 2 section" (all the way at the bottom) points to a local address: http://127.0.0.1:8080/https/#secrunletsencryptonamazonlinux2.

**Comment by drstearns** [comment]
Nice catch! Just fixed it. Should have been a relative link to the HTTPS tutorial: `../https/#sec...`
